-- OBSOLETE: The donations table is no longer used by this application.
-- Incoming donations are now read live from the wallet via RPC (listtransactions).
--
-- To remove the table from an existing installation, use the
-- Database Maintenance section in the admin panel (Admin → DB Maintenance → Drop).
-- Or run manually:
--
--   DROP TABLE IF EXISTS donations;
--
-- This file is kept for reference only.
